server:
  port: ${SERVER_PORT:9091}

spring:
  datasource:
    url: jdbc:h2:mem:~/testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      springframework:
        security: DEBUG

security:
  jwtSecret: JWTSecretKey
  jwtExpirationInMs: 604800000